name: Update Progress Bar Chart

on:
  schedule:
    - cron: "0 0 * * 1" # 毎週月曜日に実行
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: SSH 設定をデバッグ
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa
          ssh -T git@github.com

    - name: チェックアウト
      uses: actions/checkout@v3
      with:
        persist-credentials: true

    - name: セットアップ Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: 必要なパッケージをインストール
      run: |
        python -m ensurepip --upgrade
        python -m pip install --upgrade pip
        pip install matplotlib

    - name: 棒グラフを生成
      run: |
        set -x
        python generate_bar_chart.py

    - name: 生成されたグラフをコミット
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git add progress_bar_chart.png
        git commit -m "Update progress bar chart"
        git pull --rebase origin main
        git push origin HEAD:main
